export const USERLIST = [
    {
      id: 1,
      name: 'Alice Johnson',
      type: 0,
      birth: '1990-01-01',
      category: 'Admin',
      avatarUrl: '/static/mock-images/avatars/avatar_1.jpg',
    },
    {
      id: 2,
      name: 'Bob Smith',
      type: 0,
      birth: '1985-05-12',
      category: 'User',
      avatarUrl: '/static/mock-images/avatars/avatar_2.jpg',
    },
    {
      id: 3,
      name: 'Charlie Brown',
      type: 0,
      birth: '1979-09-30',
      category: 'User',
      avatarUrl: '/static/mock-images/avatars/avatar_3.jpg',
    },
    {
      id: 4,
      name: 'David Wilson',
      type: 0,
      birth: '1988-07-20',
      category: 'User',
      avatarUrl: '/static/mock-images/avatars/avatar_4.jpg',
    },
    {
      id: 5,
      name: 'Eva Green',
      type: 0,
      birth: '1992-03-15',
      category: 'User',
      avatarUrl: '/static/mock-images/avatars/avatar_5.jpg',
    },
  ];